[FAPI suite] build product-is

diff --git a/.github/workflows/fapi-oidc-conformance-test.yml b/.github/workflows/fapi-oidc-conformance-test.yml
--- a/.github/workflows/fapi-oidc-conformance-test.yml
+++ b/.github/workflows/fapi-oidc-conformance-test.yml
@@ -10,12 +10,16 @@ on:
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
     inputs:
-      tag:
-        description: 'product-is tag name'
+      build-IS:
+        description: 'Build Identity Server from wso2/product-is'
         required: false
-        default: 'v7.0.0-alpha'
+        default: 'false'
+      tag:
+        description: 'product-is release tag name. If build-IS is true, this will not be used.'
+        required: false
+        default: 'v7.0.0-alpha2'
       download-url:
-        description: 'URL to download product-is'
+        description: 'URL to download product-is. If build-IS is true, this will not be used.'
         required: false
       conformance-suite-version:
         description: 'Conformance suite release tag in https://github.com/openid-certification/conformance-suite.git'
@@ -46,35 +50,68 @@ jobs:
         pip3 install httpx
         pip3 install httplib2
         
-    - name: Download IS zip
+    - name: Get IS zip
       run: |
+        INPUT_BUILD_IS=${{github.event.inputs.build-IS}}
         INPUT_URL=${{github.event.inputs.download-url}}
         INPUT_TAG=${{github.event.inputs.tag}}
-        if [[ -z "${INPUT_URL}" ]] && [[ -z "${INPUT_TAG}" ]]; then
-          echo "Either 'tag' or 'download-url' must be provided."
-          exit 1
-        fi
-        if [[ -z "${INPUT_URL}" ]]; then
-          owner="wso2"
-          repo="product-is"
-          if [[ -z "${INPUT_TAG}" ]]; then
-            tag=${GITHUB_REF:10}
-            tag_trimmed=${tag// }
-          else
-            tag=${{github.event.inputs.tag}}
-            tag_trimmed=${tag// }
+        if [[ "${INPUT_BUILD_IS}" == "true" ]]; then
+          echo "Building IS from source..."
+          mkdir cloned-product-is
+          cd cloned-product-is
+          git clone https://github.com/wso2/product-is
+          cd product-is
+          mvn clean install -Dmaven.test.skip=true | tee mvn-build.log
+
+          REPO_BUILD_STATUS=$(cat mvn-build.log | grep "\[INFO\] BUILD" | grep -oE '[^ ]+$')
+          echo "==========================================================="
+          echo "BUILD $REPO_BUILD_STATUS"
+          echo "=========================================================="
+
+          if [[ "${REPO_BUILD_STATUS}" != "SUCCESS" ]]; then
+            exit 1
           fi
 
-          artifact="wso2is-${tag_trimmed:1}.zip"
-          echo "Tag=$tag"
-          echo "Artifact=$artifact"
-          list_asset_url="https://api.github.com/repos/${owner}/${repo}/releases/tags/${tag_trimmed}"
-          asset_url=$(curl "${list_asset_url}" | jq ".assets[] | select(.name==\"${artifact}\") | .url" | sed 's/\"//g')
-          curl -vLJO -H 'Accept: application/octet-stream' \
-           "${asset_url}"
+          # Find a zip file with a specific name format
+          zip_file=$(find . -name 'wso2is-*.zip' -type f -print -quit)
+
+          # Check if a zip file was found
+          if [[ -z "$zip_file" ]]; then
+            echo "Zip file not found"
+            exit 1
+          fi
+
+          # Do something with the zip file
+          echo "Zip file found: $zip_file"
+
+          cp "$zip_file" /../../
         else
-          curl -vLJO -H 'Accept: application/octet-stream' \
-           "${INPUT_URL}"
+          if [[ -z "${INPUT_URL}" ]] && [[ -z "${INPUT_TAG}" ]]; then
+            echo "Either 'tag' or 'download-url' must be provided."
+            exit 1
+          fi
+          if [[ -z "${INPUT_URL}" ]]; then
+            owner="wso2"
+            repo="product-is"
+            if [[ -z "${INPUT_TAG}" ]]; then
+              tag=${GITHUB_REF:10}
+              tag_trimmed=${tag// }
+            else
+              tag=${{github.event.inputs.tag}}
+              tag_trimmed=${tag// }
+            fi
+
+            artifact="wso2is-${tag_trimmed:1}.zip"
+            echo "Tag=$tag"
+            echo "Artifact=$artifact"
+            list_asset_url="https://api.github.com/repos/${owner}/${repo}/releases/tags/${tag_trimmed}"
+            asset_url=$(curl "${list_asset_url}" | jq ".assets[] | select(.name==\"${artifact}\") | .url" | sed 's/\"//g')
+            curl -vLJO -H 'Accept: application/octet-stream' \
+              "${asset_url}"
+          else
+            curl -vLJO -H 'Accept: application/octet-stream' \
+              "${INPUT_URL}"
+          fi
         fi
 
     - name: Add deployment toml configs to IS
